### ISSUE TITLE
Failed init blog and init docs

### ISSUE THREAD

**Issue by bitbut** [tighten/jigsaw#502]
jigsaw init blog and init docs command fails with following error message:

```
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --env=local --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/xxxx/www/jig/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^
```
```
Error: No valid exports main found for '/Users/xxxx/www/jig/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/xxxx/www/jig/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/xxxx/www/jig/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (/Users/xxxx/www/jig/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/xxxx/www/jig/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at /Users/xxxx/www/jig/node_modules/laravel-mix/src/components/Preprocessor.js:62:41
    at /Users/xxxx/www/jig/node_modules/laravel-mix/src/components/Preprocessor.js:77:31
    at global.tap (/Users/xxxx/www/jig/node_modules/laravel-mix/src/helpers.js:10:5)
    at /Users/xxxx/www/jig/node_modules/laravel-mix/src/components/Preprocessor.js:27:13
    at Array.forEach (<anonymous>)
    at Sass.webpackRules (/Users/xxxx/www/jig/node_modules/laravel-mix/src/components/Preprocessor.js:22:22)
    at ComponentFactory.applyRules (/Users/xxxx/www/jig/node_modules/laravel-mix/src/components/ComponentFactory.js:155:23)
    at /Users/xxxx/www/jig/node_modules/laravel-mix/src/components/ComponentFactory.js:66:48
    at /Users/xxxx/www/jig/node_modules/laravel-mix/src/Dispatcher.js:34:47
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/Users/xxxx/www/jig/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/Users/xxxx/www/jig/node_modules/laravel-mix/src/Mix.js:118:25)
    at WebpackConfig.buildRules (/Users/xxxx/www/jig/node_modules/laravel-mix/src/builder/WebpackConfig.js:90:13)
    at WebpackConfig.build (/Users/xxxx/www/jig/node_modules/laravel-mix/src/builder/WebpackConfig.js:23:14)
    at Object.<anonymous> (/Users/xxxx/www/jig/node_modules/laravel-mix/setup/webpack.config.js:29:38)
    at Module._compile (/Users/xxxx/www/jig/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (/Users/xxxx/www/jig/node_modules/v8-compile-cache/v8-compile-cache.js:161:20) {
  code: 'MODULE_NOT_FOUND'
}
```
How to reproduce the issue:

Create a new project directory, cd to project directory:

$ composer require tightenco/jigsaw
$ ./vendor/bin/jigsaw init docs
# or 
$ ./vendor/bin/jigsaw init blog

macOS Catalina 10.15.6, PHP 7.3.12, npm 6.14.8,  jigsaw 1.3.29

**Comment by bakerkretzmar** [comment]
This looks like an issue with `colorette` on some versions of Node 13.x, upgrade to Node 14 (or 13.7 if you really need 13) and it should work.

See https://github.com/jorgebucaran/colorette/issues/48#issuecomment-654669713.
