### ISSUE TITLE
init fails on `npm run dev`

### ISSUE THREAD

**Issue by ju5t** [tighten/jigsaw#604]
I'm trying to set up some documentation based on jigsaw. Here's what I did:

```bash
$ composer require tightenco/jigsaw
$ ./vendor/bin/jigsaw init docs
```

This results in an error during `npm run dev`. See the full error below:

```
> npm run dev

> dev
> mix

37% building import loader ./node_modules/css-loader/dist/cjs.jsBrowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
87% sealing module hashingnode:internal/crypto/hash:105
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at BulkUpdateDecorator.update (/Users/user/path/node_modules/webpack/lib/util/createHash.js:51:14)
    at NormalModule.updateHash (/Users/user/path/node_modules/webpack/lib/NormalModule.js:1129:8)
    at Compilation._createModuleHash (/Users/user/path/node_modules/webpack/lib/Compilation.js:3086:10)
    at Compilation.createModuleHashes (/Users/user/path/node_modules/webpack/lib/Compilation.js:3058:10)
    at /Users/user/path/node_modules/webpack/lib/Compilation.js:2335:11
    at Hook.eval [as callAsync] (eval at create (/Users/user/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/user/path/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/user/path/node_modules/webpack/lib/Compilation.js:2295:36 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.3.0

There was an error running the command 'npm run dev'
```

I couldn't find any previous issues about this. Is this something related to my environment?

**Comment by bakerkretzmar** [comment]
@ju5t for now if you can use Node 16 that should work, but we'll keep looking into this. Thanks!

**Comment by bakerkretzmar** [comment]
Or—try upgrading to the latest version of `laravel-mix`, they have a couple of fixes for this upstream.

**Comment by ju5t** [comment]
I have updated both `laravel-mix` and `laravel-mix-jigsaw`. That fixed it. Thanks for the quick reply!
